### ISSUE TITLE
import of undeclared dependency "aiohttp" is attempted even if AsyncClient is not required

### ISSUE THREAD

**Issue by Lx** [madpilot/pyptv3#2]
## Background

* The `pyptv3` package offers both blocking and non-blocking clients: `Client` & `AsyncClient`.
* Since use of `AsyncClient` is optional, the `pyptv3` package correctly does **not** declare `aiohttp` as an installation dependency.

## Problem

* When importing `pyptv3` without the intention of using the non-blocking `AsyncClient`, attempt to import `aiohttp` still occurs.
* If `aiohttp` is not installed, problems arise:

  ```
  import pyptv3
  Traceback (most recent call last):
    File "pyptv3/__init__.py", line 2, in <module>
      from .async_client import AsyncClient
    File "pyptv3/async_client.py", line 2, in <module>
      import aiohttp
  ModuleNotFoundError: No module named 'aiohttp'
  ```

## Expectation

* Import of `aiohttp` should only be attempted if `pyptv3.AsyncClient` is imported directly.
* `import pyptv3`, which occurs when non-blocking `AsyncClient` support is not needed, should **not** cause `pyptv3.AsyncClient` to be imported.
* `aiohttp` should remain an **optional** dependency as it is now.

## Workaround until issue is resolved

* Install `aiohttp` dependency manually alongside `pyptv3` even if `AsyncClient` support is not needed.

## Environment

```
$ pip -V
pip 19.0.3 from /.../pip-19.0.3-py3.7.egg/pip (python 3.7)
$ pip show pyptv3 | grep Version:
Version: 0.0.4
```

**Comment by Lx** [comment]
On further reflection, the `AsyncClient` might be better off in a separate PyPI package (perhaps `pyptv3-asyncio`?) which can depend on `pyptv3` and any `asyncio`-related dependencies.

Then projects depending on `AsyncClient` could specify `pyptv3` and `pyptv3-asyncio` as dependencies and have correct access to everything without `ImportError`s.
